### ISSUE TITLE
Regexes that can match 0 characters aren't handled properly

### ISSUE THREAD

**Issue by fabiospampinato** [kitten/reghex#7]
The following two parsers should produce the same output, in this case, but they don't:

```js
console.log ( parse ( match ( '👎' )`${/\s*/} ${/foo/}` )( 'foo' ) ); // => undefined
console.log ( parse ( match ( '👍' )`${/\s/}? ${/foo/}` )( 'foo' ) ); // => [ 'foo', tag: '👍' ]
```

**Comment by kitten** [comment]
Currently that's expected behaviour; the generated parser differentiates only between falseish and non-falseish values, hence empty strings (and empty matches) are discarded as non-matching. I'm not 100% certain that's the best, but for ignored values I typically write `(?: ${ignored}?)` which basically says that empty matches are ok (while discarding them)

**Comment by fabiospampinato** [comment]
I think it would be best to change that for a few reasons:

1. Currently `${/\s*/} ${/foo/}` and `${/\s*foo/}` mean two very different things, that doesn't look right to me and kind of breaks matchers composability.
2. Peg.js works differently, I think it would be good to align with that even just to make this library more appealing to people coming from that.
3. In the few PEG-like parsers I've read, like [this one](https://github.com/pegjs/pegjs/blob/master/examples/javascript.pegjs), people often use tokens named something like `_` that match whitespace characters, then referencing that in other tokens just works beautifully, but if potentially-0-char matchers aren't allowed now you need to write `${_}?` rather than just `${_}` everywhere, which is visually noisy and pretty error prone/easy to forget to do.

**Comment by kitten** [comment]
If PEG does it as well that's already a convincing argument 🙌 awesome! I'll try to get that in with the other batch of changes then and will bump a major then 🥳
