### ISSUE TITLE
Support for string matchers

### ISSUE THREAD

**Issue by fabiospampinato** [kitten/reghex#8]
It'd be useful if a matcher could be specified using strings also, this would make parsers a bit cleaner and easier to read as a lot of characters wouldn't need to be escaped in strings.

E.g.: `/\/\//` => `'//'`

**Comment by kitten** [comment]
I did add that initially but I then discarded it to keep the size of the core library low; could be worth readding though

**Comment by fabiospampinato** [comment]
IMO the added code for generating regexes out of strings would be minimal and worth it overall, part of the appeal of RegHex, for me at least, is that the source code of parsers looks pretty clean considering that they are written in JS, the cleaner it can get the better.

Maybe something like this would work:

```js
str => new RegExp ( str.replace ( /[\\^$.*+?()[\]{}|]/g, char => `\\${char}` ), 'y' );
```

**Comment by kitten** [comment]
I could potentially just revert this change here 🤔 https://github.com/kitten/reghex/commit/2d73f61002192c2b9f81eac70695514eca549dcb#diff-8ab41fe13597e1554b5d6b4c227b5f123ff2d6726a7f3688a8b8d1224fe1d4f3

**Comment by fabiospampinato** [comment]
That looks even better, it's probably faster than dealing with regexes.
